### ISSUE TITLE
SS Playerが見つからない

### ISSUE THREAD

**Issue by naotaro0123** [SpriteStudio/SS5PlayerForUnrealEngine4#1]
以下のチュートリアルの「3.Ss Player を選択します」でコンポーネント検索した際、SS Playerが見つからないのですが、どうしたらいいでしょうか？
最新の4.7対応プラグインとUE4.7.0 Win7を使用してます

[UE4] SpriteStudioプラグイン　Actorからの基本的な使用方法
http://historia.co.jp/archives/1639
[画像]
https://docs.google.com/document/d/1hc6kR1FIfKMmCqBtf70VzH2zyH0levYy5T5hHqemSp0/edit

**Comment by KazumasaOhashi** [comment]
ご報告ありがとうございます。
問題を修正致しましたので、最新版を取得して頂ければと思います。

**Comment by naotaro0123** [comment]
動作確認しました。ありがとうございます！
