### ISSUE TITLE
SpriteStudioプラグインのUMGモジュールによるパッケージ化エラーについて

### ISSUE THREAD

**Issue by katze7514** [SpriteStudio/SS5PlayerForUnrealEngine4#13]
# 動作環境
SpriteStudioプラグイン v1.0.5
UE4.10.1

# 問題
SpriteStudioプラグインを含んだ状態でパッケージ化をするとリンクエラーとなり、パッケージ化ができません。

原因としては、以下のAnswerHubにもある通り、UMGモジュールが依存しているHACD.libというライブラリが無いと言われてしまうためのようです。
https://answers.unrealengine.com/questions/317904/hacd-lib-missing.html

HACD.libは、エディタでのみ必要なライブラリだそうなのでUE4側のバグではあるのですが、パッケージ化を通すために一時的にでもUMG部分を無効にできる仕組みを用意していただけませんでしょうか

**Comment by KazumasaOhashi** [comment]
ご報告ありがとうございます。

当方の環境ではDevelopment/Shippingともにパッケージ化に成功してしまい、状況が再現出来ていない状態です。
（別途、サンプルプロジェクトのBPにエラーが出ていました件は修正して確認しています。こちらは次回更新時に修正したいと思います）
プラットフォームはWin64でよろしかったでしょうか？


とりあえずの対処方になりますが、UMGへの依存をなくすには、プロジェクトをC++プロジェクト化したうえで、以下の手順でソースコードを編集して下さい。

１．下記の２つのファイルを削除します
Plugins/SpriteStudio5/Source/SpriteStudio5/Private/UMG/SsPlayerWidget.cpp
Plugins/SpriteStudio5/Source/SpriteStudio5/Public/UMG/SsPlayerWidget.h

２．下記のファイルの53行目 「"UMG",」の記述を削除します
Plugins/SpriteStudio5/Source/SpriteStudio5/SpriteStudio5.Build.cs

以上、よろしくお願い致します。

**Comment by katze7514** [comment]
ご返答ありがとうございます。

調査を続けていた所、SpriteStudioプラグインは悪くなく、自分で作ったプラグインが悪さしていました。
お手数をおかけしまして、申し訳ありませんでした。
