### ISSUE TITLE
「SpriteStudio Play Settings」パネルでAutoPlayAnimPackName/AnimationNameを設定する時の挙動についての要望

### ISSUE THREAD

**Issue by katze7514** [SpriteStudio/SS5PlayerForUnrealEngine4#26]
お疲れ様です。

SsPlayerComponentのパラメータをBPエディタの詳細パネル上で設定する際に
Animationに「anime_1」を持たないAnimPackを指定することができません。
指定できるように対応をお願いしたいです。

**Comment by KazumasaOhashi** [comment]
ご報告ありがとうございます。

申し訳ありませんが、開発側で問題を再現出来ておりません。
使用されているUE4及びプラグインのバージョンは何になりますでしょうか？
また、この問題を再現可能なサンプルデータを提供して頂くことは可能でしょうか？

**Comment by DKAlpha** [comment]
現象の再現できるデータを送っていけただける場合はこちらのアドレスまでお願いいたします。
github-spritestudio@webtech.co.jp

よろしくお願いいたします。

**Comment by katze7514** [comment]
再現データを作ろうと再度試してみた所、再発しませんでした。
何か操作を間違っていたのかもしれません。申し訳ありません。

一応、発生した時のverは以下の通りです。

UE4.13.0
SpriteStudio v5.6.1
SpriteStudioPlugin v1.2.1

**Comment by DKAlpha** [comment]
再現しないという事で、こちら一度クローズさせていただきます。
よろしくお願いいたします。
